### ISSUE TITLE
Change of Zip has no affect....

### ISSUE THREAD

**Issue by goobertek** [vincep5/MMM-Pollen#2]
{
                        module: "MMM-Pollen",
                        position: "top_left",
                        header: "Pollen Forecast",
                        config: {
                        updateInterval: 3 * 60 * 60 * 1000, // every 3 hours
                        zip_code: "66215"
                                }
                },

**Comment by vincep5** [comment]
looks like they have blocked the API call.  I don't see any workarounds as of now

**Comment by vincep5** [comment]
API works sometimes and other times not so much.  A test API call that I tried today did indeed work.  Maybe try to restart the MagicMirror process so that the config picks up your changes.  Your config looked valid.
