### ISSUE TITLE
Is there any way to get rid of yesterday?

### ISSUE THREAD

**Issue by aareben** [vincep5/MMM-Pollen#3]
I don't really need yesterday's forecast so can I remove is somewhere in the code.

**Comment by vincep5** [comment]
inside the .forEach you could check for indexDay == 'Yesterday' and skip the iteration
You can modify your MMM-Pollen.js after line 68
`if (indexDay == 'Yesterday') {
return;
}`

If I hear more feedback, I could officially add it into the code as a config entry, but for now, you can modify your local code.

**Comment by aareben** [comment]
That mostly worked. Just needed to add a ' after yesterday. Thanks. I'm sure some people would agree with me but it's a great module either way.
